<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>aefc15e0-755c-4b08-be63-2357a0bda590</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="Resend" Version="0.19.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\PublishProfiles\rivel.runasp.net-WebDeploy.publishSettings.pubxml" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="publish\web.config" />
      <_ContentIncludedByDefault Remove="publish\appsettings.json" />
      <_ContentIncludedByDefault Remove="publish\RiverLine.Api.deps.json" />
      <_ContentIncludedByDefault Remove="publish\RiverLine.Api.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="publish\RiverLine.Api.staticwebassets.endpoints.json" />
    </ItemGroup>

</Project>
