// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiverLine.Api.Data;

#nullable disable

namespace RiverLine.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919181421_AddNileBerth")]
    partial class AddNileBerth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.CarrierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CarrierProfiles");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.CarrierRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrierProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationBerthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationNileBerthId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginBerthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginNileBerthId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarrierProfileId");

                    b.HasIndex("DestinationNileBerthId");

                    b.HasIndex("OriginNileBerthId");

                    b.ToTable("CarrierRoutes");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.NileBerth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Axis")
                        .HasColumnType("integer");

                    b.Property<int>("CoordinateAccuracy")
                        .HasColumnType("integer");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NileBerths");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ArabicName = "ميناء دمياط النهري",
                            Axis = 1,
                            CoordinateAccuracy = 0,
                            Governorate = "دمياط",
                            IsActive = true,
                            Latitude = 31.460344m,
                            Longitude = 31.756536m,
                            Name = "Damietta River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ArabicName = "رصيف طلخا",
                            Axis = 1,
                            CoordinateAccuracy = 0,
                            Governorate = "الدقهلية",
                            IsActive = true,
                            Latitude = 31.059511m,
                            Longitude = 31.398000m,
                            Name = "Talkha Pier",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ArabicName = "رصيف طلخا 2",
                            Axis = 1,
                            CoordinateAccuracy = 0,
                            Governorate = "الدقهلية",
                            IsActive = true,
                            Latitude = 31.048407m,
                            Longitude = 31.357553m,
                            Name = "Talkha Pier 2",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ArabicName = "رصيف زفتى النهري",
                            Axis = 1,
                            CoordinateAccuracy = 0,
                            Governorate = "الغربية",
                            IsActive = true,
                            Latitude = 30.710902m,
                            Longitude = 31.255163m,
                            Name = "Zifta River Dock",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ArabicName = "القناطر الخيرية",
                            Axis = 1,
                            CoordinateAccuracy = 1,
                            Governorate = "القليوبية",
                            IsActive = true,
                            Latitude = 30.205m,
                            Longitude = 31.126m,
                            Name = "Delta Barrage",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ArabicName = "ميناء بنها النهري",
                            Axis = 1,
                            CoordinateAccuracy = 1,
                            Governorate = "القليوبية",
                            IsActive = true,
                            Latitude = 30.466m,
                            Longitude = 31.185m,
                            Name = "Banha River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ArabicName = "آثار النبي",
                            Axis = 0,
                            CoordinateAccuracy = 0,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 30.115057m,
                            Longitude = 31.215250m,
                            Name = "Athar El Nabi",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ArabicName = "إمبابة الناقلات",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الجيزة",
                            IsActive = true,
                            Latitude = 30.062m,
                            Longitude = 31.207m,
                            Name = "Imbaba Tankers",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ArabicName = "ميناء إمبابة النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الجيزة",
                            IsActive = true,
                            Latitude = 30.076m,
                            Longitude = 31.208m,
                            Name = "Imbaba River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            ArabicName = "التبين - حجر جيري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 29.805m,
                            Longitude = 31.331m,
                            Name = "El Tebbin Limestone",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            ArabicName = "التبين - كوك",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 29.798m,
                            Longitude = 31.320m,
                            Name = "El Tebbin Coke",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            ArabicName = "التبين النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 29.800m,
                            Longitude = 31.325m,
                            Name = "El Tebbin El Nahree",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            ArabicName = "طرة - أسمنت",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 29.927m,
                            Longitude = 31.281m,
                            Name = "Tora Cement",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            ArabicName = "المسارة",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "القاهرة",
                            IsActive = true,
                            Latitude = 29.906m,
                            Longitude = 31.282m,
                            Name = "El Masara",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            ArabicName = "القومية - أسمنت",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "بني سويف",
                            IsActive = true,
                            Latitude = 29.95m,
                            Longitude = 31.20m,
                            Name = "El Kawmiya Cement",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            ArabicName = "سمالوط - أسمنت",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "المنيا",
                            IsActive = true,
                            Latitude = 28.312m,
                            Longitude = 30.711m,
                            Name = "Samalout Cement",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            ArabicName = "سمالوط - عقدة نهرية",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "المنيا",
                            IsActive = true,
                            Latitude = 28.312m,
                            Longitude = 30.711m,
                            Name = "Samalout River Node",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            ArabicName = "ميناء المنيا النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "المنيا",
                            IsActive = true,
                            Latitude = 28.109m,
                            Longitude = 30.750m,
                            Name = "Minya River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            ArabicName = "بني خالد / سمالوط",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "المنيا",
                            IsActive = true,
                            Latitude = 28.420m,
                            Longitude = 30.760m,
                            Name = "Bany Khaled / Samalout",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            ArabicName = "ميناء المنيا اللوجستي",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "المنيا",
                            IsActive = true,
                            Latitude = 28.110m,
                            Longitude = 30.745m,
                            Name = "Minya Logistics River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            ArabicName = "العقبة",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.22m,
                            Longitude = 31.18m,
                            Name = "El Akaba",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            ArabicName = "محطة أسيوط - حبوب",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.180m,
                            Longitude = 31.185m,
                            Name = "Asyut Calories Station",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            ArabicName = "ميناء أسيوط البترولي",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.18m,
                            Longitude = 31.19m,
                            Name = "Asyut Petrol Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            ArabicName = "أسيوط أسمنت - منقباد",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.215m,
                            Longitude = 31.190m,
                            Name = "Asyut Cement – Menkbad",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            ArabicName = "ميناء منقباد - أسمدة",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.218m,
                            Longitude = 31.185m,
                            Name = "Menkbad Fertilizer Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            ArabicName = "ميناء أسيوط النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسيوط",
                            IsActive = true,
                            Latitude = 27.180m,
                            Longitude = 31.183m,
                            Name = "Asyut River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            ArabicName = "ميناء سوهاج النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "سوهاج",
                            IsActive = true,
                            Latitude = 26.56m,
                            Longitude = 31.70m,
                            Name = "Sohag River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            ArabicName = "جرجا - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "سوهاج",
                            IsActive = true,
                            Latitude = 26.34m,
                            Longitude = 31.89m,
                            Name = "Gerga Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            ArabicName = "البلينا",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "سوهاج",
                            IsActive = true,
                            Latitude = 26.25m,
                            Longitude = 32.00m,
                            Name = "El Balina",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            ArabicName = "ألومنيوم النهر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 26.05m,
                            Longitude = 32.72m,
                            Name = "River Aluminum",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            ArabicName = "نجع حمادي - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 26.04m,
                            Longitude = 32.24m,
                            Name = "Nagaa Hammady Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            ArabicName = "دشنا - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 26.09m,
                            Longitude = 32.58m,
                            Name = "Dishna Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            ArabicName = "قوص - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 25.91m,
                            Longitude = 32.76m,
                            Name = "Koss Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            ArabicName = "ميناء دندرة النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 26.14m,
                            Longitude = 32.66m,
                            Name = "Dandara River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            ArabicName = "ميناء قنا النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "قنا",
                            IsActive = true,
                            Latitude = 26.16m,
                            Longitude = 32.72m,
                            Name = "Qena River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            ArabicName = "ميناء الأقصر النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الأقصر",
                            IsActive = true,
                            Latitude = 25.69m,
                            Longitude = 32.64m,
                            Name = "Luxor River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            ArabicName = "أرمنت - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الأقصر",
                            IsActive = true,
                            Latitude = 25.62m,
                            Longitude = 32.55m,
                            Name = "Armant Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            ArabicName = "ميناء إسنا النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الأقصر",
                            IsActive = true,
                            Latitude = 25.29m,
                            Longitude = 32.55m,
                            Name = "Esna River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            ArabicName = "السباعية",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "الأقصر",
                            IsActive = true,
                            Latitude = 25.52m,
                            Longitude = 32.74m,
                            Name = "El Sibaaya",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            ArabicName = "إدفو - سكر",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.98m,
                            Longitude = 32.88m,
                            Name = "Edfu Sugar",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            ArabicName = "رصيف إدفو النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.98m,
                            Longitude = 32.88m,
                            Name = "Edfu River Dock",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            ArabicName = "ميناء أسوان / العقب",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.10m,
                            Longitude = 32.90m,
                            Name = "Aswan River Port / El Akab",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            ArabicName = "ميناء أسوان النهري",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.09m,
                            Longitude = 32.90m,
                            Name = "Aswan River Port",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            ArabicName = "مصنع فيرو سيليكون",
                            Axis = 0,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.15m,
                            Longitude = 32.90m,
                            Name = "Firo-Silicon Factory",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            ArabicName = "رصيف أبو سمبل",
                            Axis = 2,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 22.34m,
                            Longitude = 31.62m,
                            Name = "Abu Simbel Pier",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            ArabicName = "توشكى / عمدة",
                            Axis = 2,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 22.80m,
                            Longitude = 31.20m,
                            Name = "Tushka / Amada",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            ArabicName = "الحديد والصلب",
                            Axis = 2,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.08m,
                            Longitude = 32.89m,
                            Name = "El Hadid & El Solb",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            ArabicName = "بحيرة ناصر / إنزال أسوان",
                            Axis = 2,
                            CoordinateAccuracy = 1,
                            Governorate = "أسوان",
                            IsActive = true,
                            Latitude = 24.09m,
                            Longitude = 32.90m,
                            Name = "Lake Nasser / Aswan Landing",
                            Type = 4
                        });
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ProposedPickupDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ShipmentRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ShipmentRequestId");

                    b.HasIndex("VesselId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoOwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("ShipmentRequestId")
                        .IsUnique();

                    b.HasIndex("VesselId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.ShipmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationBerthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationNileBerthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginBerthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginNileBerthId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CargoOwnerId");

                    b.HasIndex("DestinationNileBerthId");

                    b.HasIndex("OriginNileBerthId");

                    b.ToTable("ShipmentRequests");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CarrierProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrierProfileId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.CarrierProfile", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", "User")
                        .WithOne("CarrierProfile")
                        .HasForeignKey("RiverLine.Api.Models.Entities.CarrierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.CarrierRoute", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.CarrierProfile", "CarrierProfile")
                        .WithMany("Routes")
                        .HasForeignKey("CarrierProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.NileBerth", "DestinationNileBerth")
                        .WithMany()
                        .HasForeignKey("DestinationNileBerthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.NileBerth", "OriginNileBerth")
                        .WithMany()
                        .HasForeignKey("OriginNileBerthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierProfile");

                    b.Navigation("DestinationNileBerth");

                    b.Navigation("OriginNileBerth");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Offer", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", "Carrier")
                        .WithMany("Offers")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.ShipmentRequest", "ShipmentRequest")
                        .WithMany("Offers")
                        .HasForeignKey("ShipmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("ShipmentRequest");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Rating", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.Shipment", "Shipment")
                        .WithOne("Rating")
                        .HasForeignKey("RiverLine.Api.Models.Entities.Rating", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Shipment", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.Offer", "Offer")
                        .WithOne("Shipment")
                        .HasForeignKey("RiverLine.Api.Models.Entities.Shipment", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.ShipmentRequest", "ShipmentRequest")
                        .WithOne("Shipment")
                        .HasForeignKey("RiverLine.Api.Models.Entities.Shipment", "ShipmentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.Vessel", "Vessel")
                        .WithMany("Shipments")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("ShipmentRequest");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.ShipmentRequest", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.User", "CargoOwner")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("CargoOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.NileBerth", "DestinationNileBerth")
                        .WithMany()
                        .HasForeignKey("DestinationNileBerthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiverLine.Api.Models.Entities.NileBerth", "OriginNileBerth")
                        .WithMany()
                        .HasForeignKey("OriginNileBerthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoOwner");

                    b.Navigation("DestinationNileBerth");

                    b.Navigation("OriginNileBerth");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Vessel", b =>
                {
                    b.HasOne("RiverLine.Api.Models.Entities.CarrierProfile", "CarrierProfile")
                        .WithMany("Vessels")
                        .HasForeignKey("CarrierProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierProfile");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.CarrierProfile", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Offer", b =>
                {
                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Shipment", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.ShipmentRequest", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.User", b =>
                {
                    b.Navigation("CarrierProfile");

                    b.Navigation("Offers");

                    b.Navigation("ShipmentRequests");
                });

            modelBuilder.Entity("RiverLine.Api.Models.Entities.Vessel", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
